export const FETCH_NOWSHOWING_STARTED = 'FETCH_NOWSHOWING_STARTED';
export const FETCH_NOWSHOWING_COMPLETED = 'FETCH_NOWSHOWING_COMPLETED';
export const FETCH_NOWSHOWING_FAILED = 'FETCH_NOWSHOWING_FAILED';